# Generated by Django 5.2.11 on 2026-03-26 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='accepte_client_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation client"),
        ),
        migrations.AddField(
            model_name='facture',
            name='accepte_par_client',
            field=models.BooleanField(blank=True, null=True, verbose_name='Accepté par le client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='approuve_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='facture',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commentaire_approbation',
            field=models.TextField(blank=True, verbose_name="Commentaire d'approbation"),
        ),
        migrations.AddField(
            model_name='facture',
            name='token_approbation',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token approbation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='token_client',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('en_attente', "En attente d'approbation"), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('non_payee', 'Non payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
