# Generated by Django 5.2.11 on 2026-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_facture_accepte_client_le_facture_accepte_par_client_and_more'),
        ('taxes', '0002_pays_alter_paystaxe_options_paystaxe_pays_migre_taxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='factures', to='taxes.taxe', verbose_name='Taxes applicables'),
        ),
    ]
