# Generated by Django 5.2.11 on 2026-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_facture_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='taxes_personnalisees',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Taxes personnalisées'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
