# Generated by Django 5.2.11 on 2026-04-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_facture_taxes_personnalisees_alter_lignefacture_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='devise_choisie',
            field=models.CharField(blank=True, default='', help_text="Devise sélectionnée par l'utilisateur pour cette facture", max_length=10, verbose_name='Devise'),
        ),
    ]
