# Generated by Django 5.2.11 on 2026-04-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_facture_devise_choisie'),
    ]

    operations = [
    ]
