# Generated by Django 5.2.11 on 2026-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_add_devise_choisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_envoi_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi par email"),
        ),
    ]
