# Generated by Django 5.2.11 on 2026-03-21 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email_entreprise', models.EmailField(blank=True, max_length=254, verbose_name='Email entreprise')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profils/logos/', verbose_name="Logo de l'entreprise")),
                ('mention_legale', models.TextField(blank=True, help_text='Apparaît en bas des PDF (SIRET, RCE, etc.)', verbose_name='Mentions légales')),
                ('conditions_paiement', models.TextField(blank=True, default='Paiement à 30 jours.', verbose_name='Conditions de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
            },
        ),
    ]
