# Generated by Django 5.2.11 on 2026-04-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la configuration')),
                ('type_email', models.CharField(choices=[('principal', 'Email principal (notifications, validation, réinitialisation)'), ('factures', 'Email dédié (factures et devis)')], max_length=20, unique=True, verbose_name="Type d'email")),
                ('host', models.CharField(max_length=255, verbose_name='Serveur SMTP')),
                ('port', models.IntegerField(default=587, verbose_name='Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Utiliser SSL')),
                ('username', models.CharField(max_length=255, verbose_name="Nom d'utilisateur")),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('from_email', models.EmailField(max_length=254, verbose_name="Adresse d'expédition (From)")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('test_envoye', models.BooleanField(default=False, verbose_name='Email test envoyé')),
                ('date_dernier_test', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier test')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configurations email',
                'ordering': ['type_email'],
            },
        ),
    ]
