# Generated by Django 5.2.11 on 2026-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaysTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Pays')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code ISO')),
                ('type_taxe', models.CharField(help_text='Ex: TVA, GST, Sales Tax, IVA...', max_length=50, verbose_name='Type de taxe')),
                ('taux_defaut', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux par défaut (%)')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pays / Taxe',
                'verbose_name_plural': 'Pays / Taxes',
                'ordering': ['nom'],
            },
        ),
    ]
