# Generated by Django 5.2.11 on 2026-03-30 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Pays')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code ISO')),
                ('devise', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('devise_symbole', models.CharField(default='FCFA', max_length=5, verbose_name='Symbole devise')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('type_taxe_defaut', models.CharField(blank=True, max_length=50, verbose_name='Type de taxe par défaut')),
                ('taux_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux par défaut (%)')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='paystaxe',
            options={'ordering': ['nom'], 'verbose_name': 'Pays / Taxe (Legacy)', 'verbose_name_plural': 'Pays / Taxes (Legacy)'},
        ),
        migrations.AddField(
            model_name='paystaxe',
            name='pays_migre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.pays', verbose_name='Pays migré'),
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la taxe')),
                ('code', models.CharField(max_length=10, verbose_name='Code de la taxe')),
                ('taux', models.DecimalField(decimal_places=2, help_text='Ex: 5.00 pour TPS, 9.975 pour TVQ', max_digits=5, verbose_name='Taux (%)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('par_defaut', models.BooleanField(default=False, help_text='Cochez si cette taxe doit être pré-sélectionnée', verbose_name='Sélectionnée par défaut')),
                ('cumulative', models.BooleanField(default=False, help_text="Cochez si cette taxe s'applique sur le montant incluant les autres taxes (ex: TVQ au Québec)", verbose_name='Taxe cumulative')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='taxes.pays', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Taxe',
                'verbose_name_plural': 'Taxes',
                'ordering': ['pays', 'ordre'],
                'unique_together': {('pays', 'code')},
            },
        ),
    ]
