# Generated by Django 5.2.11 on 2026-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_pays_alter_paystaxe_options_paystaxe_pays_migre_taxe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxe',
            options={'ordering': ['pays', 'province', 'ordre'], 'verbose_name': 'Taxe', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterUniqueTogether(
            name='taxe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taxe',
            name='province',
            field=models.CharField(blank=True, help_text='Laisser vide si applicable à tout le pays (ex: TPS fédérale)', max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AlterUniqueTogether(
            name='taxe',
            unique_together={('pays', 'code', 'province')},
        ),
    ]
