# Generated by Django 5.2.11 on 2026-03-13 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_pays',
            field=models.CharField(blank=True, default='BF', max_length=2, verbose_name='Code pays (ISO)'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='client',
            name='indicatif',
            field=models.CharField(blank=True, default='+226', max_length=10, verbose_name='Indicatif téléphonique'),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province/Région'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='client',
            name='entreprise',
            field=models.CharField(blank=True, max_length=150, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.CharField(default='Burkina Faso', max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom', 'prenom'], name='clients_cli_nom_f99d14_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['code_pays'], name='clients_cli_code_pa_89ee07_idx'),
        ),
    ]
