# Generated by Django 5.2.11 on 2026-03-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_code_pays_client_date_modification_and_more'),
        ('produits', '0003_alter_produit_options_produit_taux_taxe_personnalise_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_nom_f99d14_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_email_56b9fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_code_pa_89ee07_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code_pays',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pays',
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='client',
            name='pays_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='produits.pays', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='entreprise',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='indicatif',
            field=models.CharField(choices=[('+226', '🇧🇫 Burkina Faso (+226)'), ('+225', "🇨🇮 Côte d'Ivoire (+225)"), ('+221', '🇸🇳 Sénégal (+221)'), ('+223', '🇲🇱 Mali (+223)'), ('+227', '🇳🇪 Niger (+227)'), ('+228', '🇹🇬 Togo (+228)'), ('+229', '🇧🇯 Bénin (+229)'), ('+237', '🇨🇲 Cameroun (+237)'), ('+241', '🇬🇦 Gabon (+241)'), ('+242', '🇨🇬 Congo (+242)'), ('+243', '🇨🇩 RDC (+243)'), ('+212', '🇲🇦 Maroc (+212)'), ('+213', '🇩🇿 Algérie (+213)'), ('+216', '🇹🇳 Tunisie (+216)'), ('+20', '🇪🇬 Égypte (+20)'), ('+27', '🇿🇦 Afrique du Sud (+27)'), ('+234', '🇳🇬 Nigeria (+234)'), ('+233', '🇬🇭 Ghana (+233)'), ('+254', '🇰🇪 Kenya (+254)'), ('+255', '🇹🇿 Tanzanie (+255)'), ('+256', '🇺🇬 Ouganda (+256)'), ('+250', '🇷🇼 Rwanda (+250)'), ('+251', '🇪🇹 Éthiopie (+251)'), ('+1', '🇨🇦 Canada (+1)'), ('+1', '🇺🇸 États-Unis (+1)'), ('+52', '🇲🇽 Mexique (+52)'), ('+55', '🇧🇷 Brésil (+55)'), ('+54', '🇦🇷 Argentine (+54)'), ('+57', '🇨🇴 Colombie (+57)'), ('+56', '🇨🇱 Chili (+56)'), ('+51', '🇵🇪 Pérou (+51)'), ('+58', '🇻🇪 Venezuela (+58)'), ('+44', '🇬🇧 Royaume-Uni (+44)'), ('+33', '🇫🇷 France (+33)'), ('+49', '🇩🇪 Allemagne (+49)'), ('+39', '🇮🇹 Italie (+39)'), ('+34', '🇪🇸 Espagne (+34)'), ('+351', '🇵🇹 Portugal (+351)'), ('+32', '🇧🇪 Belgique (+32)'), ('+41', '🇨🇭 Suisse (+41)'), ('+31', '🇳🇱 Pays-Bas (+31)'), ('+46', '🇸🇪 Suède (+46)'), ('+47', '🇳🇴 Norvège (+47)'), ('+45', '🇩🇰 Danemark (+45)'), ('+358', '🇫🇮 Finlande (+358)'), ('+48', '🇵🇱 Pologne (+48)'), ('+420', '🇨🇿 République Tchèque (+420)'), ('+36', '🇭🇺 Hongrie (+36)'), ('+7', '🇷🇺 Russie (+7)'), ('+90', '🇹🇷 Turquie (+90)'), ('+86', '🇨🇳 Chine (+86)'), ('+81', '🇯🇵 Japon (+81)'), ('+82', '🇰🇷 Corée du Sud (+82)'), ('+91', '🇮🇳 Inde (+91)'), ('+62', '🇮🇩 Indonésie (+62)'), ('+60', '🇲🇾 Malaisie (+60)'), ('+65', '🇸🇬 Singapour (+65)'), ('+66', '🇹🇭 Thaïlande (+66)'), ('+84', '🇻🇳 Vietnam (+84)'), ('+63', '🇵🇭 Philippines (+63)'), ('+92', '🇵🇰 Pakistan (+92)'), ('+880', '🇧🇩 Bangladesh (+880)'), ('+94', '🇱🇰 Sri Lanka (+94)'), ('+977', '🇳🇵 Népal (+977)'), ('+61', '🇦🇺 Australie (+61)'), ('+64', '🇳🇿 Nouvelle-Zélande (+64)')], default='+226', max_length=5, verbose_name='Indicatif'),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province / État / Région'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
