# Generated by Django 5.2.11 on 2026-03-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_migrer_pays_vers_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ancien_pays_id',
        ),
    ]
