# Generated by Django 5.2.11 on 2026-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_ancien_pays_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='indicatif',
            field=models.CharField(choices=[('+27', '🇿🇦 Afrique du Sud (+27)'), ('+213', '🇩🇿 Algérie (+213)'), ('+49', '🇩🇪 Allemagne (+49)'), ('+54', '🇦🇷 Argentine (+54)'), ('+61', '🇦🇺 Australie (+61)'), ('+880', '🇧🇩 Bangladesh (+880)'), ('+32', '🇧🇪 Belgique (+32)'), ('+229', '🇧🇯 Bénin (+229)'), ('+55', '🇧🇷 Brésil (+55)'), ('+226', '🇧🇫 Burkina Faso (+226)'), ('+237', '🇨🇲 Cameroun (+237)'), ('+1', '🇨🇦 Canada / 🇺🇸 États-Unis (+1)'), ('+56', '🇨🇱 Chili (+56)'), ('+86', '🇨🇳 Chine (+86)'), ('+57', '🇨🇴 Colombie (+57)'), ('+242', '🇨🇬 Congo (+242)'), ('+82', '🇰🇷 Corée du Sud (+82)'), ('+225', "🇨🇮 Côte d'Ivoire (+225)"), ('+45', '🇩🇰 Danemark (+45)'), ('+20', '🇪🇬 Égypte (+20)'), ('+34', '🇪🇸 Espagne (+34)'), ('+251', '🇪🇹 Éthiopie (+251)'), ('+358', '🇫🇮 Finlande (+358)'), ('+33', '🇫🇷 France (+33)'), ('+241', '🇬🇦 Gabon (+241)'), ('+233', '🇬🇭 Ghana (+233)'), ('+36', '🇭🇺 Hongrie (+36)'), ('+91', '🇮🇳 Inde (+91)'), ('+62', '🇮🇩 Indonésie (+62)'), ('+39', '🇮🇹 Italie (+39)'), ('+81', '🇯🇵 Japon (+81)'), ('+254', '🇰🇪 Kenya (+254)'), ('+60', '🇲🇾 Malaisie (+60)'), ('+223', '🇲🇱 Mali (+223)'), ('+212', '🇲🇦 Maroc (+212)'), ('+52', '🇲🇽 Mexique (+52)'), ('+977', '🇳🇵 Népal (+977)'), ('+227', '🇳🇪 Niger (+227)'), ('+234', '🇳🇬 Nigeria (+234)'), ('+47', '🇳🇴 Norvège (+47)'), ('+64', '🇳🇿 Nouvelle-Zélande (+64)'), ('+256', '🇺🇬 Ouganda (+256)'), ('+92', '🇵🇰 Pakistan (+92)'), ('+31', '🇳🇱 Pays-Bas (+31)'), ('+51', '🇵🇪 Pérou (+51)'), ('+63', '🇵🇭 Philippines (+63)'), ('+48', '🇵🇱 Pologne (+48)'), ('+351', '🇵🇹 Portugal (+351)'), ('+243', '🇨🇩 RDC (+243)'), ('+420', '🇨🇿 République Tchèque (+420)'), ('+44', '🇬🇧 Royaume-Uni (+44)'), ('+7', '🇷🇺 Russie (+7)'), ('+250', '🇷🇼 Rwanda (+250)'), ('+221', '🇸🇳 Sénégal (+221)'), ('+65', '🇸🇬 Singapour (+65)'), ('+94', '🇱🇰 Sri Lanka (+94)'), ('+46', '🇸🇪 Suède (+46)'), ('+41', '🇨🇭 Suisse (+41)'), ('+255', '🇹🇿 Tanzanie (+255)'), ('+66', '🇹🇭 Thaïlande (+66)'), ('+228', '🇹🇬 Togo (+228)'), ('+216', '🇹🇳 Tunisie (+216)'), ('+90', '🇹🇷 Turquie (+90)'), ('+58', '🇻🇪 Venezuela (+58)'), ('+84', '🇻🇳 Vietnam (+84)')], default='+226', max_length=5, verbose_name='Indicatif'),
        ),
    ]
