# Generated by Django 5.2.11 on 2026-03-26 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_remove_client_clients_cli_nom_f99d14_idx_and_more'),
        ('produits', '0004_alter_province_options_alter_pays_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(blank=True, default='', max_length=100, verbose_name='Pays')),
                ('type_taxe', models.CharField(blank=True, default='TVA', max_length=50, verbose_name='Type de taxe')),
                ('taux_taxe', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de taxe (%)')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validite', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve_superieur', 'Approuvé par supérieur'), ('rejete_superieur', 'Rejeté par supérieur'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='devis/pdf/')),
                ('transforme_en_facture', models.BooleanField(default=False)),
                ('approuve_le', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('commentaire_approbation', models.TextField(blank=True, verbose_name="Commentaire d'approbation")),
                ('accepte_par_client', models.BooleanField(blank=True, null=True, verbose_name='Accepté par le client')),
                ('accepte_client_le', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation client")),
                ('token_approbation', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token approbation')),
                ('token_client', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token client')),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='clients.client')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='TVA (%)')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='produits.produit', verbose_name='Produit du catalogue')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
            },
        ),
    ]
