# Generated by Django 5.2.11 on 2026-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='pays',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='devis',
            name='taux_taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_taxe',
            field=models.CharField(blank=True, default='TVA', max_length=50, verbose_name='Type de taxe'),
        ),
    ]
