# Generated by Django 5.2.11 on 2026-03-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
        ('taxes', '0002_pays_alter_paystaxe_options_paystaxe_pays_migre_taxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='devis', to='taxes.taxe', verbose_name='Taxes applicables'),
        ),
    ]
