# Generated by Django 5.2.11 on 2026-04-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_devis_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='devise_choisie',
            field=models.CharField(blank=True, default='', help_text="Devise sélectionnée par l'utilisateur pour ce devis", max_length=10, verbose_name='Devise'),
        ),
    ]
