# Generated by Django 5.2.11 on 2026-03-13 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_devis_pays_devis_taux_taxe_devis_type_taxe'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='produits.produit', verbose_name='Produit du catalogue'),
        ),
    ]
