# Generated by Django 5.2.11 on 2026-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_devis_devise_choisie'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='taxes_personnalisees',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Taxes personnalisées'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='TVA (%)'),
        ),
    ]
