# Generated by Django 5.2.11 on 2026-03-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('devise', models.CharField(default='FCFA', max_length=3)),
                ('symbole_devise', models.CharField(default='FCFA', max_length=5)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='produit',
            name='taux_tva',
        ),
        migrations.AddField(
            model_name='produit',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.pays', verbose_name='Pays de vente'),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('nom', models.CharField(max_length=100)),
                ('tps', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='TPS (%)')),
                ('tvq', models.DecimalField(decimal_places=2, default=9.975, max_digits=5, verbose_name='TVQ (%)')),
                ('tvh', models.BooleanField(default=False, verbose_name='TVH (Taxe harmonisée)')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='produits.pays')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['nom'],
                'unique_together': {('pays', 'code')},
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.province', verbose_name='Province (Canada)'),
        ),
    ]
