# Generated by Django 5.2.11 on 2026-03-13 04:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_pays_remove_produit_taux_tva_produit_pays_province_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_taxe_personnalise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Laissez à 0 pour utiliser le taux par défaut', max_digits=5, verbose_name='Taux personnalisé (%)'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Code pays (ISO)'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='devise',
            field=models.CharField(default='FCFA', max_length=3, verbose_name='Code devise (ISO)'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom du pays'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='symbole_devise',
            field=models.CharField(default='FCFA', max_length=5, verbose_name='Symbole devise'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Produit actif'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix HT'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock initial'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_alerte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(choices=[('piece', 'Pièce'), ('heure', 'Heure'), ('jour', 'Jour'), ('mois', 'Mois'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube'), ('kg', 'Kilogramme'), ('litre', 'Litre'), ('forfait', 'Forfait'), ('service', 'Service')], default='piece', max_length=20, verbose_name='Unité de vente'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Code province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.CreateModel(
            name='TypeTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la taxe')),
                ('code', models.CharField(max_length=20, verbose_name='Code (TVA, GST, etc.)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_taxe_composee', models.BooleanField(default=False, verbose_name='Est une taxe composée?')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_taxe', to='produits.pays')),
            ],
            options={
                'verbose_name': 'Type de taxe',
                'verbose_name_plural': 'Types de taxes',
                'ordering': ['pays', 'nom'],
                'unique_together': {('pays', 'code')},
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='type_taxe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.typetaxe', verbose_name='Type de taxe'),
        ),
        migrations.CreateModel(
            name='TauxTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région/Province')),
                ('code_region', models.CharField(blank=True, max_length=10, verbose_name='Code région')),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux (%)')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='Taux par défaut')),
                ('type_taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux', to='produits.typetaxe')),
            ],
            options={
                'verbose_name': 'Taux de taxe',
                'verbose_name_plural': 'Taux de taxes',
                'ordering': ['type_taxe__pays', 'region'],
                'unique_together': {('type_taxe', 'region')},
            },
        ),
    ]
