# Generated by Django 5.2.11 on 2026-03-21 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_options_produit_taux_taxe_personnalise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['nom']},
        ),
        migrations.AlterField(
            model_name='pays',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='pays',
            name='devise',
            field=models.CharField(default='FCFA', max_length=3),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pays',
            name='symbole_devise',
            field=models.CharField(default='FCFA', max_length=5),
        ),
        migrations.AlterField(
            model_name='produit',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.province'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_alerte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taux_taxe_personnalise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_taxe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.typetaxe'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(blank=True, default='piece', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='province',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='province',
            name='tps',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='province',
            name='tvh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='tvq',
            field=models.DecimalField(decimal_places=2, default=9.975, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tauxtaxe',
            name='code_region',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tauxtaxe',
            name='est_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tauxtaxe',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tauxtaxe',
            name='taux',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='typetaxe',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='typetaxe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='typetaxe',
            name='est_taxe_composee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typetaxe',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='UniteVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom affiché')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='Unité par défaut')),
                ('ordre', models.PositiveSmallIntegerField(default=99, verbose_name="Ordre d'affichage")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unites_vente', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur (vide = global)')),
            ],
            options={
                'verbose_name': 'Unité de vente',
                'verbose_name_plural': 'Unités de vente',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.unitevente', verbose_name='Unité de vente'),
        ),
    ]
