# -*- coding: utf-8 -*-
"""Peuple automatiquement le référentiel Pays/Taxes du catalogue produits
(généré depuis fixtures_all_data.json) et les unités de vente globales.
Idempotent : sûr à rejouer, ne duplique rien."""
from django.db import migrations

PAYS_DATA = [{'code': 'BF', 'devise': 'XOF', 'nom': 'Burkina Faso', 'pk': 1, 'symbole_devise': 'FCFA'},
 {'code': 'CI', 'devise': 'XOF', 'nom': "Côte d'Ivoire", 'pk': 2, 'symbole_devise': 'FCFA'},
 {'code': 'SN', 'devise': 'XOF', 'nom': 'Sénégal', 'pk': 3, 'symbole_devise': 'FCFA'},
 {'code': 'ML', 'devise': 'XOF', 'nom': 'Mali', 'pk': 4, 'symbole_devise': 'FCFA'},
 {'code': 'NE', 'devise': 'XOF', 'nom': 'Niger', 'pk': 5, 'symbole_devise': 'FCFA'},
 {'code': 'TG', 'devise': 'XOF', 'nom': 'Togo', 'pk': 6, 'symbole_devise': 'FCFA'},
 {'code': 'BJ', 'devise': 'XOF', 'nom': 'Bénin', 'pk': 7, 'symbole_devise': 'FCFA'},
 {'code': 'CM', 'devise': 'XAF', 'nom': 'Cameroun', 'pk': 8, 'symbole_devise': 'FCFA'},
 {'code': 'GA', 'devise': 'XAF', 'nom': 'Gabon', 'pk': 9, 'symbole_devise': 'FCFA'},
 {'code': 'CG', 'devise': 'XAF', 'nom': 'Congo-Brazzaville', 'pk': 10, 'symbole_devise': 'FCFA'},
 {'code': 'CD',
  'devise': 'CDF',
  'nom': 'République Démocratique du Congo',
  'pk': 11,
  'symbole_devise': 'FC'},
 {'code': 'MA', 'devise': 'MAD', 'nom': 'Maroc', 'pk': 12, 'symbole_devise': 'DH'},
 {'code': 'DZ', 'devise': 'DZD', 'nom': 'Algérie', 'pk': 13, 'symbole_devise': 'DA'},
 {'code': 'TN', 'devise': 'TND', 'nom': 'Tunisie', 'pk': 14, 'symbole_devise': 'DT'},
 {'code': 'EG', 'devise': 'EGP', 'nom': 'Égypte', 'pk': 15, 'symbole_devise': '£'},
 {'code': 'ZA', 'devise': 'ZAR', 'nom': 'Afrique du Sud', 'pk': 16, 'symbole_devise': 'R'},
 {'code': 'NG', 'devise': 'NGN', 'nom': 'Nigeria', 'pk': 17, 'symbole_devise': '₦'},
 {'code': 'GH', 'devise': 'GHS', 'nom': 'Ghana', 'pk': 18, 'symbole_devise': '₵'},
 {'code': 'KE', 'devise': 'KES', 'nom': 'Kenya', 'pk': 19, 'symbole_devise': 'KSh'},
 {'code': 'TZ', 'devise': 'TZS', 'nom': 'Tanzanie', 'pk': 20, 'symbole_devise': 'TSh'},
 {'code': 'UG', 'devise': 'UGX', 'nom': 'Ouganda', 'pk': 21, 'symbole_devise': 'USh'},
 {'code': 'RW', 'devise': 'RWF', 'nom': 'Rwanda', 'pk': 22, 'symbole_devise': 'FRw'},
 {'code': 'ET', 'devise': 'ETB', 'nom': 'Éthiopie', 'pk': 23, 'symbole_devise': 'Br'},
 {'code': 'CA', 'devise': 'CAD', 'nom': 'Canada', 'pk': 24, 'symbole_devise': '$'},
 {'code': 'US', 'devise': 'USD', 'nom': 'États-Unis', 'pk': 25, 'symbole_devise': '$'},
 {'code': 'MX', 'devise': 'MXN', 'nom': 'Mexique', 'pk': 26, 'symbole_devise': '$'},
 {'code': 'BR', 'devise': 'BRL', 'nom': 'Brésil', 'pk': 27, 'symbole_devise': 'R$'},
 {'code': 'AR', 'devise': 'ARS', 'nom': 'Argentine', 'pk': 28, 'symbole_devise': '$'},
 {'code': 'CO', 'devise': 'COP', 'nom': 'Colombie', 'pk': 29, 'symbole_devise': '$'},
 {'code': 'CL', 'devise': 'CLP', 'nom': 'Chili', 'pk': 30, 'symbole_devise': '$'},
 {'code': 'PE', 'devise': 'PEN', 'nom': 'Pérou', 'pk': 31, 'symbole_devise': 'S/'},
 {'code': 'VE', 'devise': 'VES', 'nom': 'Venezuela', 'pk': 32, 'symbole_devise': 'Bs'},
 {'code': 'GB', 'devise': 'GBP', 'nom': 'Royaume-Uni', 'pk': 33, 'symbole_devise': '£'},
 {'code': 'FR', 'devise': 'EUR', 'nom': 'France', 'pk': 34, 'symbole_devise': '€'},
 {'code': 'DE', 'devise': 'EUR', 'nom': 'Allemagne', 'pk': 35, 'symbole_devise': '€'},
 {'code': 'IT', 'devise': 'EUR', 'nom': 'Italie', 'pk': 36, 'symbole_devise': '€'},
 {'code': 'ES', 'devise': 'EUR', 'nom': 'Espagne', 'pk': 37, 'symbole_devise': '€'},
 {'code': 'PT', 'devise': 'EUR', 'nom': 'Portugal', 'pk': 38, 'symbole_devise': '€'},
 {'code': 'BE', 'devise': 'EUR', 'nom': 'Belgique', 'pk': 39, 'symbole_devise': '€'},
 {'code': 'CH', 'devise': 'CHF', 'nom': 'Suisse', 'pk': 40, 'symbole_devise': 'Fr'},
 {'code': 'NL', 'devise': 'EUR', 'nom': 'Pays-Bas', 'pk': 41, 'symbole_devise': '€'},
 {'code': 'SE', 'devise': 'SEK', 'nom': 'Suède', 'pk': 42, 'symbole_devise': 'kr'},
 {'code': 'NO', 'devise': 'NOK', 'nom': 'Norvège', 'pk': 43, 'symbole_devise': 'kr'},
 {'code': 'DK', 'devise': 'DKK', 'nom': 'Danemark', 'pk': 44, 'symbole_devise': 'kr'},
 {'code': 'FI', 'devise': 'EUR', 'nom': 'Finlande', 'pk': 45, 'symbole_devise': '€'},
 {'code': 'PL', 'devise': 'PLN', 'nom': 'Pologne', 'pk': 46, 'symbole_devise': 'zł'},
 {'code': 'CZ', 'devise': 'CZK', 'nom': 'République Tchèque', 'pk': 47, 'symbole_devise': 'Kč'},
 {'code': 'HU', 'devise': 'HUF', 'nom': 'Hongrie', 'pk': 48, 'symbole_devise': 'Ft'},
 {'code': 'RU', 'devise': 'RUB', 'nom': 'Russie', 'pk': 49, 'symbole_devise': '₽'},
 {'code': 'TR', 'devise': 'TRY', 'nom': 'Turquie', 'pk': 50, 'symbole_devise': '₺'},
 {'code': 'CN', 'devise': 'CNY', 'nom': 'Chine', 'pk': 51, 'symbole_devise': '¥'},
 {'code': 'JP', 'devise': 'JPY', 'nom': 'Japon', 'pk': 52, 'symbole_devise': '¥'},
 {'code': 'KR', 'devise': 'KRW', 'nom': 'Corée du Sud', 'pk': 53, 'symbole_devise': '₩'},
 {'code': 'IN', 'devise': 'INR', 'nom': 'Inde', 'pk': 54, 'symbole_devise': '₹'},
 {'code': 'ID', 'devise': 'IDR', 'nom': 'Indonésie', 'pk': 55, 'symbole_devise': 'Rp'},
 {'code': 'MY', 'devise': 'MYR', 'nom': 'Malaisie', 'pk': 56, 'symbole_devise': 'RM'},
 {'code': 'SG', 'devise': 'SGD', 'nom': 'Singapour', 'pk': 57, 'symbole_devise': '$'},
 {'code': 'TH', 'devise': 'THB', 'nom': 'Thaïlande', 'pk': 58, 'symbole_devise': '฿'},
 {'code': 'VN', 'devise': 'VND', 'nom': 'Vietnam', 'pk': 59, 'symbole_devise': '₫'},
 {'code': 'PH', 'devise': 'PHP', 'nom': 'Philippines', 'pk': 60, 'symbole_devise': '₱'},
 {'code': 'PK', 'devise': 'PKR', 'nom': 'Pakistan', 'pk': 61, 'symbole_devise': '₨'},
 {'code': 'BD', 'devise': 'BDT', 'nom': 'Bangladesh', 'pk': 62, 'symbole_devise': '৳'},
 {'code': 'LK', 'devise': 'LKR', 'nom': 'Sri Lanka', 'pk': 63, 'symbole_devise': '₨'},
 {'code': 'NP', 'devise': 'NPR', 'nom': 'Népal', 'pk': 64, 'symbole_devise': '₨'},
 {'code': 'AU', 'devise': 'AUD', 'nom': 'Australie', 'pk': 65, 'symbole_devise': '$'},
 {'code': 'NZ', 'devise': 'NZD', 'nom': 'Nouvelle-Zélande', 'pk': 66, 'symbole_devise': '$'}]

PROVINCE_DATA = [{'code': 'QC', 'nom': 'Québec', 'pays': 24, 'pk': 1, 'tps': '5.00', 'tvh': False, 'tvq': '9.98'},
 {'code': 'ON', 'nom': 'Ontario', 'pays': 24, 'pk': 2, 'tps': '0.00', 'tvh': True, 'tvq': '0.00'},
 {'code': 'BC',
  'nom': 'Colombie-Britannique',
  'pays': 24,
  'pk': 3,
  'tps': '5.00',
  'tvh': False,
  'tvq': '7.00'},
 {'code': 'AB', 'nom': 'Alberta', 'pays': 24, 'pk': 4, 'tps': '5.00', 'tvh': False, 'tvq': '0.00'},
 {'code': 'MB', 'nom': 'Manitoba', 'pays': 24, 'pk': 5, 'tps': '5.00', 'tvh': False, 'tvq': '7.00'},
 {'code': 'SK',
  'nom': 'Saskatchewan',
  'pays': 24,
  'pk': 6,
  'tps': '5.00',
  'tvh': False,
  'tvq': '6.00'},
 {'code': 'NB',
  'nom': 'Nouveau-Brunswick',
  'pays': 24,
  'pk': 7,
  'tps': '0.00',
  'tvh': True,
  'tvq': '0.00'},
 {'code': 'NS',
  'nom': 'Nouvelle-Écosse',
  'pays': 24,
  'pk': 8,
  'tps': '0.00',
  'tvh': True,
  'tvq': '0.00'},
 {'code': 'PE',
  'nom': 'Île-du-Prince-Édouard',
  'pays': 24,
  'pk': 9,
  'tps': '0.00',
  'tvh': True,
  'tvq': '0.00'},
 {'code': 'NL',
  'nom': 'Terre-Neuve-et-Labrador',
  'pays': 24,
  'pk': 10,
  'tps': '0.00',
  'tvh': True,
  'tvq': '0.00'},
 {'code': 'YT', 'nom': 'Yukon', 'pays': 24, 'pk': 11, 'tps': '5.00', 'tvh': False, 'tvq': '0.00'},
 {'code': 'NT',
  'nom': 'Territoires du Nord-Ouest',
  'pays': 24,
  'pk': 12,
  'tps': '5.00',
  'tvh': False,
  'tvq': '0.00'},
 {'code': 'NU', 'nom': 'Nunavut', 'pays': 24, 'pk': 13, 'tps': '5.00', 'tvh': False, 'tvq': '0.00'}]

TYPETAXE_DATA = [{'code': 'TVA',
  'description': 'Taxe sur la valeur ajoutée - taux standard',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 34,
  'pk': 1},
 {'code': 'TVA-R',
  'description': 'TVA taux réduit',
  'est_taxe_composee': False,
  'nom': 'TVA réduite',
  'pays': 34,
  'pk': 2},
 {'code': 'MwSt',
  'description': 'Taxe sur la valeur ajoutée allemande',
  'est_taxe_composee': False,
  'nom': 'Mehrwertsteuer',
  'pays': 35,
  'pk': 3},
 {'code': 'VAT',
  'description': 'UK Value Added Tax',
  'est_taxe_composee': False,
  'nom': 'Value Added Tax',
  'pays': 33,
  'pk': 4},
 {'code': 'TPS',
  'description': 'Taxe fédérale canadienne',
  'est_taxe_composee': False,
  'nom': 'TPS (Taxe sur les produits et services)',
  'pays': 24,
  'pk': 5},
 {'code': 'TVQ',
  'description': 'Taxe provinciale québécoise',
  'est_taxe_composee': False,
  'nom': 'TVQ (Taxe de vente du Québec)',
  'pays': 24,
  'pk': 6},
 {'code': 'TVH',
  'description': 'Taxe harmonisée (TPS + TVP)',
  'est_taxe_composee': True,
  'nom': 'TVH (Taxe de vente harmonisée)',
  'pays': 24,
  'pk': 7},
 {'code': 'ST',
  'description': 'State Sales Tax',
  'est_taxe_composee': False,
  'nom': 'Sales Tax',
  'pays': 25,
  'pk': 8},
 {'code': 'TVA',
  'description': 'TVA Burkina Faso',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 1,
  'pk': 9},
 {'code': 'TVA',
  'description': "TVA Côte d'Ivoire",
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 2,
  'pk': 10},
 {'code': 'TVA',
  'description': 'TVA Sénégal',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 3,
  'pk': 11},
 {'code': 'TVA',
  'description': 'TVA Mali',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 4,
  'pk': 12},
 {'code': 'TVA',
  'description': 'TVA Niger',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 5,
  'pk': 13},
 {'code': 'TVA',
  'description': 'TVA Togo',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 6,
  'pk': 14},
 {'code': 'TVA',
  'description': 'TVA Bénin',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 7,
  'pk': 15},
 {'code': 'TVA',
  'description': 'TVA Cameroun',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 8,
  'pk': 16},
 {'code': 'TVA',
  'description': 'TVA Gabon',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 9,
  'pk': 17},
 {'code': 'TVA',
  'description': 'TVA Maroc',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 12,
  'pk': 18},
 {'code': 'TVA',
  'description': 'TVA Tunisie',
  'est_taxe_composee': False,
  'nom': 'Taxe sur la valeur ajoutée',
  'pays': 14,
  'pk': 19},
 {'code': 'VAT',
  'description': 'South Africa VAT',
  'est_taxe_composee': False,
  'nom': 'Value Added Tax',
  'pays': 16,
  'pk': 20},
 {'code': 'VAT',
  'description': 'Nigeria VAT',
  'est_taxe_composee': False,
  'nom': 'Value Added Tax',
  'pays': 17,
  'pk': 21},
 {'code': 'GST',
  'description': 'Indian GST',
  'est_taxe_composee': False,
  'nom': 'Goods and Services Tax',
  'pays': 54,
  'pk': 22},
 {'code': 'ICMS',
  'description': 'Imposto sobre Circulação de Mercadorias',
  'est_taxe_composee': False,
  'nom': 'ICMS',
  'pays': 27,
  'pk': 23},
 {'code': 'ISS',
  'description': 'Imposto Sobre Serviços',
  'est_taxe_composee': False,
  'nom': 'ISS',
  'pays': 27,
  'pk': 24},
 {'code': 'IPI',
  'description': 'Imposto sobre Produtos Industrializados',
  'est_taxe_composee': False,
  'nom': 'IPI',
  'pays': 27,
  'pk': 25},
 {'code': 'GST',
  'description': 'Australian GST',
  'est_taxe_composee': False,
  'nom': 'Goods and Services Tax',
  'pays': 65,
  'pk': 26},
 {'code': 'GST',
  'description': 'New Zealand GST',
  'est_taxe_composee': False,
  'nom': 'Goods and Services Tax',
  'pays': 66,
  'pk': 27},
 {'code': 'CT',
  'description': 'Japanese Consumption Tax',
  'est_taxe_composee': False,
  'nom': 'Consumption Tax',
  'pays': 52,
  'pk': 28},
 {'code': 'IVA',
  'description': 'Impuesto al Valor Agregado',
  'est_taxe_composee': False,
  'nom': 'IVA',
  'pays': 26,
  'pk': 29}]

TAUXTAXE_DATA = [{'code_region': 'FR',
  'est_defaut': True,
  'pk': 1,
  'region': 'France métropolitaine',
  'taux': '20.00',
  'type_taxe': 1},
 {'code_region': 'COR',
  'est_defaut': False,
  'pk': 2,
  'region': 'Corse',
  'taux': '10.00',
  'type_taxe': 1},
 {'code_region': 'FR',
  'est_defaut': True,
  'pk': 3,
  'region': 'France',
  'taux': '5.50',
  'type_taxe': 2},
 {'code_region': 'DE',
  'est_defaut': True,
  'pk': 4,
  'region': 'Allemagne',
  'taux': '19.00',
  'type_taxe': 3},
 {'code_region': 'DE-R',
  'est_defaut': False,
  'pk': 5,
  'region': 'Allemagne réduit',
  'taux': '7.00',
  'type_taxe': 3},
 {'code_region': 'UK',
  'est_defaut': True,
  'pk': 6,
  'region': 'Royaume-Uni',
  'taux': '20.00',
  'type_taxe': 4},
 {'code_region': 'CA',
  'est_defaut': True,
  'pk': 7,
  'region': 'Canada',
  'taux': '5.00',
  'type_taxe': 5},
 {'code_region': 'QC',
  'est_defaut': True,
  'pk': 8,
  'region': 'Québec',
  'taux': '9.98',
  'type_taxe': 6},
 {'code_region': 'ON',
  'est_defaut': True,
  'pk': 9,
  'region': 'Ontario',
  'taux': '13.00',
  'type_taxe': 7},
 {'code_region': 'NB',
  'est_defaut': False,
  'pk': 10,
  'region': 'Nouveau-Brunswick',
  'taux': '15.00',
  'type_taxe': 7},
 {'code_region': 'NS',
  'est_defaut': False,
  'pk': 11,
  'region': 'Nouvelle-Écosse',
  'taux': '15.00',
  'type_taxe': 7},
 {'code_region': 'PE',
  'est_defaut': False,
  'pk': 12,
  'region': 'Île-du-Prince-Édouard',
  'taux': '15.00',
  'type_taxe': 7},
 {'code_region': 'NL',
  'est_defaut': False,
  'pk': 13,
  'region': 'Terre-Neuve',
  'taux': '15.00',
  'type_taxe': 7},
 {'code_region': 'CA',
  'est_defaut': True,
  'pk': 14,
  'region': 'California',
  'taux': '7.25',
  'type_taxe': 8},
 {'code_region': 'NY',
  'est_defaut': False,
  'pk': 15,
  'region': 'New York',
  'taux': '8.88',
  'type_taxe': 8},
 {'code_region': 'TX',
  'est_defaut': False,
  'pk': 16,
  'region': 'Texas',
  'taux': '6.25',
  'type_taxe': 8},
 {'code_region': 'FL',
  'est_defaut': False,
  'pk': 17,
  'region': 'Florida',
  'taux': '6.00',
  'type_taxe': 8},
 {'code_region': 'BF',
  'est_defaut': True,
  'pk': 18,
  'region': 'Burkina Faso',
  'taux': '18.00',
  'type_taxe': 9},
 {'code_region': 'CI',
  'est_defaut': True,
  'pk': 19,
  'region': "Côte d'Ivoire",
  'taux': '18.00',
  'type_taxe': 10},
 {'code_region': 'SN',
  'est_defaut': True,
  'pk': 20,
  'region': 'Sénégal',
  'taux': '18.00',
  'type_taxe': 11},
 {'code_region': 'ML',
  'est_defaut': True,
  'pk': 21,
  'region': 'Mali',
  'taux': '18.00',
  'type_taxe': 12},
 {'code_region': 'NE',
  'est_defaut': True,
  'pk': 22,
  'region': 'Niger',
  'taux': '19.00',
  'type_taxe': 13},
 {'code_region': 'TG',
  'est_defaut': True,
  'pk': 23,
  'region': 'Togo',
  'taux': '18.00',
  'type_taxe': 14},
 {'code_region': 'BJ',
  'est_defaut': True,
  'pk': 24,
  'region': 'Bénin',
  'taux': '18.00',
  'type_taxe': 15},
 {'code_region': 'CM',
  'est_defaut': True,
  'pk': 25,
  'region': 'Cameroun',
  'taux': '19.25',
  'type_taxe': 16},
 {'code_region': 'GA',
  'est_defaut': True,
  'pk': 26,
  'region': 'Gabon',
  'taux': '18.00',
  'type_taxe': 17},
 {'code_region': 'MA',
  'est_defaut': True,
  'pk': 27,
  'region': 'Maroc',
  'taux': '20.00',
  'type_taxe': 18},
 {'code_region': 'TN',
  'est_defaut': True,
  'pk': 28,
  'region': 'Tunisie',
  'taux': '19.00',
  'type_taxe': 19},
 {'code_region': 'ZA',
  'est_defaut': True,
  'pk': 29,
  'region': 'Afrique du Sud',
  'taux': '15.00',
  'type_taxe': 20},
 {'code_region': 'NG',
  'est_defaut': True,
  'pk': 30,
  'region': 'Nigeria',
  'taux': '7.50',
  'type_taxe': 21},
 {'code_region': 'IN',
  'est_defaut': True,
  'pk': 31,
  'region': 'Inde standard',
  'taux': '18.00',
  'type_taxe': 22},
 {'code_region': 'IN-R',
  'est_defaut': False,
  'pk': 32,
  'region': 'Inde réduit',
  'taux': '12.00',
  'type_taxe': 22},
 {'code_region': 'SP',
  'est_defaut': True,
  'pk': 33,
  'region': 'São Paulo',
  'taux': '18.00',
  'type_taxe': 23},
 {'code_region': 'RJ',
  'est_defaut': False,
  'pk': 34,
  'region': 'Rio de Janeiro',
  'taux': '18.00',
  'type_taxe': 23},
 {'code_region': 'BR',
  'est_defaut': True,
  'pk': 35,
  'region': 'Brésil',
  'taux': '5.00',
  'type_taxe': 24},
 {'code_region': 'AU',
  'est_defaut': True,
  'pk': 36,
  'region': 'Australie',
  'taux': '10.00',
  'type_taxe': 26},
 {'code_region': 'NZ',
  'est_defaut': True,
  'pk': 37,
  'region': 'Nouvelle-Zélande',
  'taux': '15.00',
  'type_taxe': 27},
 {'code_region': 'JP',
  'est_defaut': True,
  'pk': 38,
  'region': 'Japon',
  'taux': '10.00',
  'type_taxe': 28},
 {'code_region': 'MX',
  'est_defaut': True,
  'pk': 39,
  'region': 'Mexique',
  'taux': '16.00',
  'type_taxe': 29}]

UNITES_BASE = [('piece', 'Pièce'),
 ('unite', 'Unité'),
 ('lot', 'Lot'),
 ('paire', 'Paire'),
 ('douzaine', 'Douzaine'),
 ('carton', 'Carton'),
 ('boite', 'Boîte'),
 ('sac', 'Sac'),
 ('sachet', 'Sachet'),
 ('palette', 'Palette'),
 ('colis', 'Colis'),
 ('pack', 'Pack'),
 ('kg', 'Kilogramme'),
 ('g', 'Gramme'),
 ('tonne', 'Tonne'),
 ('litre', 'Litre'),
 ('ml', 'Millilitre'),
 ('m3', 'Mètre cube'),
 ('m2', 'Mètre carré'),
 ('ml_lin', 'Mètre linéaire'),
 ('heure', 'Heure'),
 ('jour', 'Jour'),
 ('semaine', 'Semaine'),
 ('mois', 'Mois'),
 ('annee', 'Année'),
 ('forfait', 'Forfait'),
 ('service', 'Service'),
 ('prestation', 'Prestation'),
 ('licence', 'Licence'),
 ('abonnement', 'Abonnement')]


def seed(apps, schema_editor):
    Pays = apps.get_model('produits', 'Pays')
    Province = apps.get_model('produits', 'Province')
    TypeTaxe = apps.get_model('produits', 'TypeTaxe')
    TauxTaxe = apps.get_model('produits', 'TauxTaxe')
    UniteVente = apps.get_model('produits', 'UniteVente')

    pays_map = {}
    for row in PAYS_DATA:
        row = dict(row)
        old_pk = row.pop('pk')
        obj, _ = Pays.objects.get_or_create(code=row.pop('code'), defaults=row)
        pays_map[old_pk] = obj

    for row in PROVINCE_DATA:
        row = dict(row)
        row.pop('pk', None)
        pays = pays_map.get(row.pop('pays'))
        if pays is None:
            continue
        Province.objects.get_or_create(pays=pays, code=row.pop('code'), defaults=row)

    typetaxe_map = {}
    for row in TYPETAXE_DATA:
        row = dict(row)
        old_pk = row.pop('pk')
        pays = pays_map.get(row.pop('pays'))
        if pays is None:
            continue
        obj, _ = TypeTaxe.objects.get_or_create(pays=pays, code=row.pop('code'), defaults=row)
        typetaxe_map[old_pk] = obj

    for row in TAUXTAXE_DATA:
        row = dict(row)
        row.pop('pk', None)
        type_taxe = typetaxe_map.get(row.pop('type_taxe'))
        if type_taxe is None:
            continue
        TauxTaxe.objects.get_or_create(
            type_taxe=type_taxe, region=row.get('region', ''), defaults=row,
        )

    for ordre, (code, nom) in enumerate(UNITES_BASE):
        UniteVente.objects.get_or_create(
            user=None, code=code, defaults={'nom': nom, 'ordre': ordre},
        )


def unseed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_province_options_alter_pays_code_and_more'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
